### ISSUE TITLE
Filler TR card issue

### ISSUE THREAD

**Issue by vedirah** [travleev/numjuggler#6]
There is an issue that sometimes if a cell's fill card has a tr translation, the fill card becomes the tr number, and inconsistent parentheses appear. And the original fill number appears a few lines above within the cell description, replacing a ')'.

Eg: FILL=141 (163)
becomes: FILL=163 ())

This issue was spotted when running remh mode on E-Lite and affected only 2 cells.

[after.txt](https://github.com/travleev/numjuggler/files/4651562/after.txt)
[before.txt](https://github.com/travleev/numjuggler/files/4651563/before.txt)

**Comment by travleev** [comment]
Thank you for reporting this issue. To my knowledge, the "remh" mode has its own card parsing algorithm thathas been tested on C-lite and C-model (see docs/remh).

To check wether this is only "remh" issue, could you please try the "renum" and "nofill" modes with your input file, e.g.:

```
>numjuggler --mode renum -t 10 -u 10 input > output1
>numjuggler --mode nofill -u 141 input > output2
```

**Comment by travleev** [comment]
Also note: there is a test input file, [nested_complement.i](https://github.com/travleev/numjuggler/blob/master/travis_tests/remh/nested_complement.i) that contains similar construction, `FILL=140  (79)`. Does this example work correctly with your numjuggler?

**Comment by vedirah** [comment]
The issue does not appear to be isolated to _remh_. The issue persists with _renum_ and there is a similar issue with _nofill_ (parentheses are lost on lines 68 & 69 in the attached document).

The _nested_complement.i_ test input works correctly for me.

The only unusual thing about the problem cells that i can see is that they have in-line comments directly after the opening bracket:
`           ) ($ OUTER SHAPE OF LOWER PORT STUB, CENTRAL`
this may be the source of the issue.

[renum.txt](https://github.com/travleev/numjuggler/files/4661606/renum.txt)
[nofill.txt](https://github.com/travleev/numjuggler/files/4661611/nofill.txt)

**Comment by travleev** [comment]
I can't repeat the error, at least with the above input file and with numjuggler version 2.43.34 that is available from PyPI. 

As the input file I took `before.txt` attached to the issue description (1-st message above) and added a title card as the 1-st line (for reference attached below). I also used an empy python3 environment to ensure that numjuggler from pypi is used:

```
>conda create --name test_i6 python=3.7       # create new empty python3 environment
>conda activate test_i6                       # make the environment active
>pip install numjuggler --no-cache-dir        # install numjuggler, ensure that pypi is used
>numjuggler --version                         # check numjuggler's version

>numjuggler --mode renum -u 10 -t 10 before.txt > after_renum.txt
>numjuggler --mode nofill -u 141     before.txt > after_nofill.txt
```
(the above is under ubuntu 18.04, conda 4.6.7)

Can you repeat these steps and still get the error? What is the output of `numjuggler --version` when you get the error?

[after_nofill.txt](https://github.com/travleev/numjuggler/files/4665980/after_nofill.txt)
[after_renum.txt](https://github.com/travleev/numjuggler/files/4665981/after_renum.txt)
[before.txt](https://github.com/travleev/numjuggler/files/4665982/before.txt)

**Comment by vedirah** [comment]
I no longer get the error using version 2.42.34.
I was using version 2.42a29 previously.
Thank you
