### ISSUE TITLE
Specify encoding="cp1251" on opening MCNP files

### ISSUE THREAD

**Issue by dvp2015** [travleev/numjuggler#9]
In the module parser files are opened in default encoding, which is 'utf-8'. However, MCNP files are usually generated on Windows (by SuperMC, for example). So, the files may contain byte sequences which cause errors on attempt to read them as unicode. We have to specifiy encoding="cp1251" explicitly to avoid these issues and to avoid efforts on cleaning the files from these unreadable otherwise characters.

**Comment by travleev** [comment]
See implementation in [fix-open-encoding](/travleev/numjuggler/tree/fix-open-encoding) branch, based on your pull request #10. Now it passes through already defined tests in [travis_tests](/travleev/numjuggler/tree/fix-open-encoding/travis_tests), both for Python2.7 and Python3.7 on Linux.

Can you please provide an example input file that requires cp1251 encoding, which I can add it to the tests?

**Comment by travleev** [comment]
Hello dvp2015!

could you please provide an example of cp-1251-encoded input file, that I can add to the tests? After that (assuming the tests are successful) I will merge fix-open-encoding branch into master and close this issue.

**Comment by dvp2015** [comment]
Any MCNP model code containing non ASCII characters created in Windows with some ANSYS encoding cannot be read in Python on Linux with default encoding. For instance, all the models generated with SuperMC have these ANSYS characters. Or one can add a comment to model in Russian or whatever not English language being on Windows.On Windows Python defalut encoding is some ANSYS code page and this is not an issue.On Linux Python default encoding is UTF-8 and Python is not able to read these files without explicit specification of encoding to some ANSYS code page.So, if you want your Python code to work on LInux, from one side,  and, from another side, handle MCNP models created on Windows without special care on encoding, then you have to specify encoding="cp1251".
I've attached the file for test, but the tests may be restricted to Linux environment.

HTH, Dmiry
    On Sunday, February 13, 2022, 04:17:28 PM GMT+3, Anton Travleev ***@***.***> wrote:  
 
 


Hello dvp2015!

could you please provide an example of cp-1251-encoded input file, that I can add to the tests? After that (assuming the tests are successful) I will merge fix-open-encoding branch into master and close this issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
